version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    ports:
      - "6333:6333" # Port dla API
      - "6334:6334" # Port dla gRPC
    volumes:
      - ./qdrant_data:/qdrant/data # Persystentne dane
    restart: always
